window.DISEASE_CODE_DB = [
  {
    code: "E780",
    officialName: "순수 고콜레스테롤혈증",
    displayName: "고지혈증",
    category: "내분비·대사질환",
    disclosureGroup: "30일 이상 투약",
    defaultVisitType: "통원",
    chronic: true,
  },
  {
    code: "E785",
    officialName: "고지질혈증",
    displayName: "고지혈증",
    category: "내분비·대사질환",
    disclosureGroup: "30일 이상 투약",
    defaultVisitType: "통원",
    chronic: true,
  },
  {
    code: "N400",
    officialName: "전립선비대증",
    displayName: "전립선비대증/전립선염",
    category: "비뇨생식기질환",
    disclosureGroup: "30일 이상 투약",
    defaultVisitType: "통원",
    chronic: true,
  },
  {
    code: "N401",
    officialName: "요로폐색을 동반한 전립선비대증",
    displayName: "전립선비대증/전립선염",
    category: "비뇨생식기질환",
    disclosureGroup: "30일 이상 투약",
    defaultVisitType: "통원",
    chronic: true,
  },
  {
    code: "G470",
    officialName: "불면증",
    displayName: "불면증",
    category: "정신·신경계질환",
    disclosureGroup: "30일 이상 투약",
    defaultVisitType: "통원",
    chronic: true,
  },
  {
    code: "F510",
    officialName: "비기질성 불면증",
    displayName: "불면증",
    category: "정신·신경계질환",
    disclosureGroup: "30일 이상 투약",
    defaultVisitType: "통원",
    chronic: true,
  },
  {
    code: "I10",
    officialName: "본태성 고혈압",
    displayName: "고혈압",
    category: "순환기질환",
    disclosureGroup: "30일 이상 투약",
    defaultVisitType: "통원",
    chronic: true,
  },
  {
    code: "I109",
    officialName: "기타 및 상세불명의 원발성 고혈압",
    displayName: "고혈압",
    category: "순환기질환",
    disclosureGroup: "30일 이상 투약",
    defaultVisitType: "통원",
    chronic: true,
  },
  {
    code: "F410",
    officialName: "공황장애",
    displayName: "공황장애",
    category: "정신·신경계질환",
    disclosureGroup: "30일 이상 투약",
    defaultVisitType: "통원",
    chronic: true,
  },
  {
    code: "G311",
    officialName: "달리 분류되지 않은 뇌의 노년변성",
    displayName: "뇌 노년변성",
    category: "정신·신경계질환",
    disclosureGroup: "30일 이상 투약",
    defaultVisitType: "통원",
    chronic: true,
  },
  {
    code: "M170",
    officialName: "양쪽 원발성 무릎관절증",
    displayName: "무릎관절증",
    category: "근골격계질환",
    disclosureGroup: "7일 이상 치료",
    defaultVisitType: "통원",
    chronic: true,
  },
  {
    code: "J042",
    officialName: "급성 후두기관염",
    displayName: "감기/상기도감염",
    category: "호흡기질환",
    disclosureGroup: "단기진료 확인",
    defaultVisitType: "통원",
    chronic: false,
  },
  {
    code: "E11",
    officialName: "2형 당뇨병",
    displayName: "당뇨",
    category: "내분비·대사질환",
    disclosureGroup: "30일 이상 투약",
    defaultVisitType: "통원",
    chronic: true,
  },
  {
    code: "K053",
    officialName: "만성 치주염",
    displayName: "치주염",
    category: "치과질환",
    disclosureGroup: "7일 이상 치료",
    defaultVisitType: "통원",
    chronic: false,
  },
  {
    code: "K0531",
    officialName: "만성 치주염",
    displayName: "치주염",
    category: "치과질환",
    disclosureGroup: "7일 이상 치료",
    defaultVisitType: "통원",
    chronic: false,
  },
  {
    code: "J060",
    officialName: "급성 후두인두염",
    displayName: "감기/상기도감염",
    category: "호흡기질환",
    disclosureGroup: "단기진료 확인",
    defaultVisitType: "통원",
    chronic: false,
  },
  {
    code: "J069",
    officialName: "상세불명의 급성 상기도감염",
    displayName: "감기/상기도감염",
    category: "호흡기질환",
    disclosureGroup: "단기진료 확인",
    defaultVisitType: "통원",
    chronic: false,
  },
  {
    code: "M234",
    officialName: "무릎의 내부장애",
    displayName: "반달연골(무릎관절) 수술",
    category: "근골격계질환",
    disclosureGroup: "입원수술",
    defaultVisitType: "입원",
    chronic: false,
  },
  {
    code: "A41",
    officialName: "기타 패혈증",
    displayName: "감염성 질환 확인 필요",
    category: "감염성 질환",
    disclosureGroup: "검토 필요",
    defaultVisitType: "확인 필요",
    chronic: false,
    reviewOnly: true,
  },
  {
    code: "O71",
    officialName: "기타 산과적 외상",
    displayName: "임신·출산 계열 확인 필요",
    category: "임신·출산 관련 코드",
    disclosureGroup: "검토 필요",
    defaultVisitType: "확인 필요",
    chronic: false,
    reviewOnly: true,
    excluded: true,
  },
  {
    code: "V96",
    officialName: "무동력항공기 사고",
    displayName: "대표질환 아님",
    category: "외인코드",
    disclosureGroup: "본문 제외",
    defaultVisitType: "해당 없음",
    chronic: false,
    excluded: true,
  },
  {
    code: "U04",
    officialName: "특수목적 코드",
    displayName: "대표질환 아님",
    category: "특수목적 코드",
    disclosureGroup: "본문 제외",
    defaultVisitType: "해당 없음",
    chronic: false,
    excluded: true,
  },
];
